spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:rgbdb
    driver-class-name: org.h2.Driver
    username: sa
    platform: h2
    password:
  jpa:
    hibernate:
      ddl-auto: validate
